Triathlon/Controllers/AthleteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Triathlon.DAL;
using Triathlon.ViewModels;
using Triathlon.Models;

namespace Triathlon.Controllers
{
    public class AthleteController : Controller
    {
        private RaceContext db = new RaceContext();

        // GET: Athlete
        public ActionResult Index(string sortOrder)
        {
            return View(db.Athletes.ToList());
        }

        // GET: Athlete/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        // GET: Athlete/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Athlete/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AthleteID,FirstName,LastName,Gender,Email,DOB,CreatedAt,FitnessLevel,FitnessGoal")] Athlete athlete)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Athletes.Add(athlete);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
                return View(athlete);
        }

        // GET: Athlete/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        // POST: Athlete/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AthleteID,FirstName,LastName,Gender,Email,DOB,CreatedAt,FitnessLevel,FitnessGoal")] Athlete athlete)
        {
            if (ModelState.IsValid)
            {
                db.Entry(athlete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(athlete);
        }

        // GET: Athlete/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError=false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Oops! Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        // POST: Athlete/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Athlete athlete = db.Athletes.Find(id);
                db.Athletes.Remove(athlete);
                db.SaveChanges();
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Triathlon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Triathlon.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to Triple Threat";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Triathlon/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Triathlon.DAL;
using Triathlon.ViewModels;
using Triathlon.Models;

namespace Triathlon.Controllers
{
    public class WorkoutController : Controller
    {
        private RaceContext db = new RaceContext();

        // GET: Workout
        public ActionResult Index()
        {
            var workouts = db.Workouts.Include(w => w.Athlete);
            return View(workouts.ToList());
        }

        // GET: Workout/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workout workout = db.Workouts.Find(id);
            if (workout == null)
            {
                return HttpNotFound();
            }
            return View(workout);
        }

        // GET: Workout/Create
        public ActionResult Create()
        {
            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "FirstName");
            return View();
        }

        // POST: Workout/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WorkoutID,AthleteID,WorkoutDescription,WorkoutDate,WorkoutDistance,WorkoutIntensity,WorkoutCategory")] Workout workout)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Workouts.Add(workout);
                    db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "FirstName", workout.AthleteID);
            return View(workout);
        }

        // GET: Workout/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workout workout = db.Workouts.Find(id);
            if (workout == null)
            {
                return HttpNotFound();
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "FirstName", workout.AthleteID);
            return View(workout);
        }

        // POST: Workout/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorkoutID,AthleteID,WorkoutDescription,WorkoutDate,WorkoutDistance,WorkoutIntensity,WorkoutCategory")] Workout workout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workout).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "FirstName", workout.AthleteID);
            return View(workout);
        }

        // GET: Workout/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workout workout = db.Workouts.Find(id);
            if (workout == null)
            {
                return HttpNotFound();
            }
            return View(workout);
        }

        // POST: Workout/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Workout workout = db.Workouts.Find(id);
            db.Workouts.Remove(workout);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Triathlon/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="main-intro">
    <img id="main-image" src="~/images/workout.jpg" alt="Image of women working out">
    <h1 class="main-header">About Log It</h1>
</div>

<div>
    <div>
        <h2><i class="fa fa-question-circle" aria-hidden="true"></i>What is Log It?</h2>
        <p>
            Log It is designed to help you keep track of your clients, like a digital paper workout journal.
            With a minimalistic approach and a clean, easy-to-use interface, Log It allows you to stay concentrated on the things that really matter. Give it a try. We know you'll love it!
        </p>
    </div>
    <div>
        <h2><i class="fa fa-thumbs-up" aria-hidden="true"></i>Why people love it</h2>
        <p>
            We've put together a great combination of simplicity and usability.
            Other workout apps take a simple thing and over complicate it. We believe that a workout log should do just what it says: log your client's workouts. We keep Simple Workout Log simple by avoiding all the unnecessary extras. A workout log should be quick and easy to use in the gym without getting in your way, or slowing you down.
        </p>
    </div>
</div>

Triathlon/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Triathlon/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="main-intro">
    <img id="main-image" class="front-page" src="~/images/meghan-holmes-779221-unsplash.jpg" alt="Background image of a trainer with a client at gym">
    <h1 class="main-header">Welcome back! Let's <span class="logo-text"><strong>Log It</strong></span></h1>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Keep track of your clients!</h2>
        <p>Log it makes it easy to update all of your client's information. All in one convenient location. </p>
        <p><a>@Html.ActionLink("GO EXPLORE", "Index", "Athlete")</a></p>
    </div>
    <div class="col-md-6">
        <h2>Update your client's workouts!</h2>
        <p>View and keep track of the hard work your clients are up to.</p>
        <p><a>@Html.ActionLink("UPDATE THEIR PROGRESS", "Index", "Workout")</a></p>
    </div>
</div>